### ISSUE TITLE
Implement Monoid[Event] instance

### ISSUE THREAD

**Issue by FrancoAra** [scalaz/scalaz-reactive#10]
As seen on page 8 of the paper http://conal.net/papers/push-pull-frp/

**Comment by kolov** [comment]
I started working on it, racing two IOs in the  Event.merge implementation.

**Comment by kolov** [comment]
I wonder how to proceed with the current algebra which does not include effect type parameter, but we want to use ZIO. Once in ZIO, the values can't be retreived back. E.g.:

```def merge(v: Event[A]): Event[A] = {

    val winner: IO[Nothing,  Either[Time, Time]] =
      IO.point(value.time()).map(Left[Time, Time](_)).race(
        IO.point(value.time()).map(Right[Time, Time](_))
      ).attempt.map(_.right.get) // oops, how to handle errors?

    // If we could get the value out of th IO, we could go like this:
    val result: Either[Time, Time] = ???
    result match {
      case Left(t) =>
        val r:  Reactive[A] = v.value.force()
        Event( Future((t, Reactive(r.head, r.tail))))
      case Right(t) =>
        val r:  Reactive[A] = value.force()
        Event( Future((t, Reactive(r.head, r.tail))))
    }
  }```

**Comment by kolov** [comment]
If we make all () => A parameters IO[Nothing, A], or F[A], implementing the merge would be easy.

**Comment by FrancoAra** [comment]
@kolov why don't we try this for now: `Future[+A] = IO[Nothing, A]`

**Comment by kolov** [comment]
Why do we keep Time and A separate? What about`Future[+A](IO[Nothing, (Time,A)])`.

**Comment by kolov** [comment]
But indeed, I prefer to start with `IO` and think about `F[_]` later.

**Comment by kolov** [comment]
Implemented monoid when `Future[+A] = IO[Nothing, A]`
