### ISSUE TITLE
Make a simple example using current api

### ISSUE THREAD

**Issue by FrancoAra** [scalaz/scalaz-reactive#12]
Several other FRP libraries (Haskell) have simple examples, code one or two using our current API in a new package for now

**Comment by kolov** [comment]
I would recommend this as a starting point: https://wiki.haskell.org/FRP_explanation_using_reactive-banana.

It is a simple example with a lot of explanation about every step.

**Comment by kolov** [comment]
An example of an accumulation behaviour built from stdin input Event works, but using `Behavour.ap()` breaks the code. `Behavour.ap()` must be fixed

**Comment by kolov** [comment]
There are two simple examples - TwoTickers and Synthesizer.
