### ISSUE TITLE
Fix type class instances

### ISSUE THREAD

**Issue by FrancoAra** [scalaz/scalaz-reactive#6]
The code is not compiling because of the type class instances of Functor/Applicative/Monad are split, make a single type class which overrides all necessary methods, please check that we don't lose the desired semantics (Monad implements map in terms of point and bind, but this might not be what we want, so we might need to override it)

**Comment by kolov** [comment]
Compile errors fixed in https://github.com/scalaz/scalaz-reactive/pull/5

**Comment by kolov** [comment]
Merged the PR unreviewed to fix the broken build.

**Comment by FrancoAra** [comment]
cool
